- hosts: all
  become: true
  become_method: sudo
  roles:
  - cluster_setup
  tags: [ setup, cluster_setup ]

- hosts: masters
  become: true
  become_method: sudo
  roles:
  - cluster_init
  tags: [ init, cluster_init ]