- hosts: bastion
  become: true
  become_method: sudo
  roles:
    - docker
    - proxy-nginx
  tags: [ webserver ]

- hosts: masters
  become: true
  become_method: sudo
  roles:
    - nginx-app
  tags: [ webserver ]