- name: Packages installation
  ansible.builtin.include_tasks: setup_packages.yml
  tags: [ packages_install, common_packages ]

- name: Kernel configuration
  ansible.builtin.include_tasks: setup_kernel.yml
  tags: [ kernel_configuration ]

- name: Kubeadm configuration
  ansible.builtin.include_tasks: setup_kubeadm.yml
  tags: [ kubeadm_configuration ]

- name: Cri-o configuration 
  ansible.builtin.include_tasks: setup_crio.yml
  tags: [ crio_configuration ]

- name: Helm configuration
  ansible.builtin.include_tasks: setup_helm.yml
  tags: [ helm_configuration ]
