- name: Combine all packages
  set_fact:
    packages: "{{ default_packages + extended_packages | default([]) }}"
  tags: [ packages_install, common_packages ]

- name: Installation of all packages
  ansible.builtin.apt:
    name: "{{ packages }}" 
    state: present
  tags: [ packages_install, common_packages ]
