- name: Check if cluster already initialised
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_init

- name: Kubeadm init
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: not k8s_init.stat.exists
  register: kubeadm_init

- name: Add KUBECONFIG env to /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: export KUBECONFIG=/etc/kubernetes/admin.conf
    create: true

- name: Export KUBECONFIG for current session
  set_fact:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Apply flannel
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: not k8s_init.stat.exists


- name: Enable execute worker nodes
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  ignore_errors: true
  when: not k8s_init.stat.exists

