GITLAB_CONFIG_PATH: "/etc/gitlab/config"
GITLAB_LOGS_PATH:   "/var/log/gitlab"
GITLAB_DATA_PATH:   "/var/opt/gitlab"

container_name:   gitlab
container_image: gitlab/gitlab-ce:18.2.0-ce.0

restart_policy: always

shm_size: 256m

volumes:
  - "{{ GITLAB_CONFIG_PATH }}:/etc/gitlab"
  - "{{ GITLAB_LOGS_PATH }}:/var/log/gitlab"
  - "{{ GITLAB_DATA_PATH }}:/var/opt/gitlab" 

env:
  GITLAB_ROOT_EMAIL: "{{ gitlab_root_email }}"
  GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
  GITLAB_OMNIBUS_CONFIG: "puma['worker_processes'] = 0"

ports:
  - "80:80"
  - "2222:22"